services:
  suddenrun:
    image: k5rv/suddenrun:latest
    container_name: suddenrun
    ports:
      - "8081:8081"
    networks:
      - spring
      - postgres
    environment:
      - SPRING_PROFILES_ACTIVE=docker
    depends_on:
      - postgres

  postgres:
    container_name: postgres
    image: postgres
    environment:
      POSTGRES_USER: suddenrun
      POSTGRES_PASSWORD: suddenrun
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  spring:
    driver: bridge

volumes:
  postgres:
