server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: spotifyrun
  cloud:
    openfeign:
      client:
        config:
          spotify:
            url: http://127.0.0.1:${wiremock.server.port}/v1
            logger-level: basic

spotifyrun:
  playlist:
    details:
      name: "Running Workout"
      description: "Music for your training based on Spotify recommendations and specific audio features"
      size: 50
    features:
      min-tempo: "120"
      max-tempo: "140"
      min-energy: "0.65"
  client:
    requests:
      get-user-top-tracks:
        limit: 50
        offset: 0
        time-range: MEDIUM_TERM
      get-recommendations:
        limit: 50

logging:
  level:
    com.ksaraev.spotifyrun: INFO
    org.springframework.web: INFO
