server:
  port: 8081
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: never

spring:
  application:
    name: spotifyrun
  security:
    oauth2:
      client:
        registration:
          spotify:
            client-name: spotify
            client-id: client-id-value
            client-secret: client-secret-value
            provider: spotify
            client-authentication-method: client_secret_basic
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user-read-email, user-top-read, playlist-modify-public, playlist-modify-private
        provider:
          spotify:
            authorization-uri: https://accounts.spotify.com/authorize?show_dialog=false
            token-uri: https://accounts.spotify.com/api/token
            user-info-uri: https://api.spotify.com/v1/me
            user-name-attribute: display_name
  cloud:
    openfeign:
      client:
        config:
          spotify:
            url: https://api.spotify.com/v1
            logger-level: full
      oauth2:
        enabled: true
        clientRegistrationId: spotify

spotifyrun:
  playlist:
    details:
      name: "Running Workout"
      description: "Music for your training based on Spotify recommendations and specific audio features"
      size: 50
    features:
      min-tempo: "185"
      max-tempo: "205"
      min-energy: "0.65"
  client:
    requests:
      get-user-top-tracks:
        limit: 50
        offset: 0
        time-range: MEDIUM_TERM
      get-recommendations:
        limit: 50

logging:
  level:
    com.ksaraev.spotifyrun: ERROR
