apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: spotifyrun-ingress
  namespace: default
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/scheme: internet-facing
spec:
  rules:
    - http:
        paths:
          - path: /app
            pathType: Prefix
            backend:
              service:
                name: spotifyrun
                port:
                  number: 80
          - path: /app/oauth2/authorization/spotify
            pathType: Exact
            backend:
              service:
                name: spotifyrun
                port:
                  number: 80
          - path: /app/login/oauth2/code/spotify
            pathType: Exact
            backend:
              service:
                name: spotifyrun
                port:
                  number: 80
          - path: /app/api/v1/playlists
            pathType: Exact
            backend:
              service:
                name: spotifyrun
                port:
                  number: 80
          - path: /app/actuator/health
            pathType: Exact
            backend:
              service:
                name: spotifyrun
                port:
                  number: 80
