apiVersion: v1
kind: Service
metadata:
  name: suddenrun
  annotations:
    alb.ingress.kubernetes.io/target-type: ip
spec:
  selector:
    app: suddenrun
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8081
  type: LoadBalancer
