# nonk8s
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spotifyrun
  region: eu-north-1
  version: "1.26"

vpc:
  subnets:
    private:
      eu-north-1a: { id: "subnet-0dcd57df286c188f3" }
      eu-north-1b: { id: "subnet-07de3ecefd3ba5e20" }

managedNodeGroups:
  - name: spotifyrun
    labels: { role: worker }
    instanceType: t3.small
    desiredCapacity: 2
    privateNetworking: true
    minSize: 1
    maxSize: 2
    volumeSize: 5
    ssh:
      allow: true
      publicKeyPath: ~/.ssh/ec2_id_rsa.pub
    tags:
      nodegroup-role: worker
    iam:
      withAddonPolicies:
        autoScaler: true
    propagateASGTags: true
