# nonk8s
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: spotifyrun-cluster
  region: eu-north-1
  version: "1.25"
managedNodeGroups:
  - name: primary
    instanceType: t2.small
    minSize: 1
    maxSize: 2
    spot: true